# -*- coding: utf-8 -*-
"""addtwonumber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeoH9Sz5psA1fmWZe1GaX2--J8fQAg1S
"""

a = 10
b = 20

sum = a + b

print("Sum =", sum)